#配置数据库的连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 192.168.153.137
    port: 6379
  rabbitmq:
    addresses: 192.168.153.139
    port: 15672
    username: admin
    password: 123

#mybatis的相关配置
mybatis:
  configuration:
    #java实体类中驼峰命名和数据库中字段下划线对应
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #告诉程序mybatis的xml文件的存在
  mapper-locations: classpath:mapper/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
  port: 8081
